// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jakrdzecyeihuimaqoph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impha3JkemVjeWVpaHVpbWFxb3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MTA5MDUsImV4cCI6MjA2MjI4NjkwNX0.B4ucQrMQgsSBIyC76ipyc7nlxL5OzbOXq8tbpLSjbM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);